lib/phones_collection_web/router.ex
defmodule PhonesCollectionWeb.Router do
  use SiemensCollection.Web, :router
  use Addict.RoutesHelper

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    addict :routes
  end

  scope "/", PhonesCollectionWeb do
    pipe_through :browser

    scope "/profile" do
      get "/", ProfileController, :edit
      put "/", ProfileController, :update
      delete "/:id", ProfileController, :delete
    end
    scope "/deals", assigns: %{filter: "successful"} do
      get "/successful", DealController, :index, as: :successful_deal
    end
    scope "/deals", assigns: %{filter: "all"} do
      get "/all", DealController, :index, as: :all_deal
    end
    scope "/deals", assigns: %{filter: "failed"} do
      get "/failed", DealController, :index, as: :failed_deal
    end
    resources "/deals", DealController
    get "/deals/:deal_id/item", ItemController, :new

    scope "/collections", as: :collections do
      get "/", CollectionController, :index
      scope "/:user_id" do
        resources "/", ItemController
        scope "/:item_id/images" do
          get "/new", PictureController, :new
          post "/", PictureController, :create
          delete "/:id", PictureController, :delete
          post "/:id/rotate/:direction", PictureController, :rotate
          put "/:id/set_cover", PictureController, :set_cover
        end
      end
    end

    resources "/", BrandController, except: [:show] do
      resources "/series", SeriesController, except: [:index, :show]
    end

    scope "/:brand_id", as: :catalog do
      resources "/", PhoneController
      scope "/:phone_id" do
        resources "/", PhoneEditionController, except: [:index]
        get "/:edition_id/set_main", PhoneController, :set_main_edition
        get "/:edition_id/add_to_collection", ItemController, :new
        scope "/:edition_id/images" do
          get "/new", PictureController, :new
          post "/", PictureController, :create
          delete "/:id", PictureController, :delete
          post "/:id/rotate/:direction", PictureController, :rotate
          put "/:id/set_cover", PictureController, :set_cover
        end
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SiemensCollection do
  #   pipe_through :api
  # end
end

lib/phones_collection_web/controllers/phone_controller.ex
defmodule PhonesCollectionWeb.PhoneController do
  use SiemensCollection.Web, :controller

  alias PhonesCollectionWeb.{Phone, PhoneEdition, Item}

  plug PhonesCollectionWeb.Plugs.CheckAdminRights when action in [:new, :create, :edit, :update, :delete, :set_main_edition]

  plug :scrub_params, "phone" when action in [:create, :update]
  plug PhonesCollectionWeb.Plugs.SetBrand

  def index(conn, _params) do
    brand_id = conn.assigns.brand.id
    query = Phone |> Phone.for_brand(brand_id) |> Phone.editions_count
    query = from query, preload: [:series, [main_edition: [:cover, :pictures]]]
    query = from query, order_by: [asc: :name]
    phones = Repo.all(query)

    # Refactor this please

    phones_by_series = phones
    |> Enum.group_by(fn e ->
                        [elem(e, 0).series_id,
                         (if elem(e, 0).series, do: elem(e, 0).series.name, else: nil)]
                     end)
    |> Enum.sort(fn e1, e2 -> Enum.at(elem(e2, 0), 1) |> case do
                                                        nil -> Enum.at(elem(e1, 0), 1) > Enum.at(elem(e2, 0), 1)
                                                        _ -> Enum.at(elem(e1, 0), 1) < Enum.at(elem(e2, 0), 1)
                                                      end
                 end)

    render(conn, "index.html", phones_by_series: phones_by_series)
  end

  def new(conn, _params) do
    brands = Repo.all(PhonesCollectionWeb.Brand)
    changeset = Phone.changeset_on_create(%Phone{phone_editions: [%PhoneEdition{}]})
    series = Repo.all(from s in PhonesCollectionWeb.Series, where: s.brand_id == ^conn.assigns.brand.id)
    render(conn, "new.html", brands: brands, series: series, changeset: changeset)
  end

  def create(conn, %{"phone" => phone_params}) do
    changeset = Phone.changeset_on_create(%Phone{}, phone_params)

    case Repo.insert(changeset) do
      {:ok, phone} ->
        # set main edition
        edition = Enum.at phone.phone_editions, 0
        changeset = Phone.changeset(phone, %{main_edition_id: edition.id})
        {:ok, _} = Repo.update(changeset)

        redirect_path = if conn.params["save_and_upload"] != nil do
          Routes.catalog_picture_path(conn, :new, conn.assigns.brand.id, phone.id, edition.id)
        else
          Routes.catalog_phone_path(conn, :index, conn.assigns.brand.id)
        end

        conn
        |> put_flash(:info, "Phone created successfully.")
        |> redirect(to: redirect_path)
      {:error, changeset} ->
        brands = Repo.all(PhonesCollectionWeb.Brand)
        series = Repo.all(from s in PhonesCollectionWeb.Series, where: s.brand_id == ^conn.assigns.brand.id)
        render(conn, "new.html", brands: brands, series: series, changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    phone = Repo.get!(Phone, id) |> Repo.preload([:brand, main_edition: [:pictures, :cover]])
    query = from pe in PhoneEdition, where: pe.phone_id == ^phone.id, preload: [:phone, :pictures, :cover]
    editions = Repo.all(query)
    main_edition = if phone.main_edition != nil do
      phone.main_edition
    else
      List.first editions
    end
    render(conn, "show.html", phone: phone, phone_edition: main_edition, editions: editions)
  end

  def edit(conn, %{"id" => id}) do
    brands = Repo.all(PhonesCollectionWeb.Brand)
    phone = Repo.get!(Phone, id)
    changeset = Phone.changeset(phone)
    series = Repo.all(from s in PhonesCollectionWeb.Series, where: s.brand_id == ^conn.assigns.brand.id)
    render(conn, "edit.html", brands: brands, series: series, phone: phone, changeset: changeset)
  end

  def update(conn, %{"id" => id, "phone" => phone_params}) do
    phone = Repo.get!(Phone, id)
    changeset = Phone.changeset(phone, phone_params)

    case Repo.update(changeset) do
      {:ok, phone} ->
        conn
        |> put_flash(:info, "Phone updated successfully.")
        |> redirect(to: Routes.catalog_phone_path(conn, :show, conn.assigns.brand.id, phone))
      {:error, changeset} ->
        brands = Repo.all(PhonesCollectionWeb.Brand)
        series = Repo.all(from s in PhonesCollectionWeb.Series, where: s.brand_id == ^conn.assigns.brand.id)
        render(conn, "edit.html", brands: brands, series: series, phone: phone, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    phone = Repo.get!(Phone, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(phone)

    conn
    |> put_flash(:info, "Phone deleted successfully.")
    |> redirect(to: Routes.catalog_phone_path(conn, :index, conn.assigns.brand.id))
  end

  def set_main_edition(conn, %{"phone_id" => id, "edition_id" => edition_id}) do
    phone = Repo.get!(Phone, id)
    changeset = Phone.changeset(phone, %{main_edition_id: edition_id})

    case Repo.update(changeset) do
      {:ok, phone} ->
        conn
        |> put_flash(:info, "Main edition updated successfully.")
        |> redirect(to: Routes.catalog_phone_path(conn, :show, conn.assigns.brand.id, phone))
      {:error, changeset} ->
        render(conn, "edit.html", phone: phone, changeset: changeset)
    end
  end

end

lib/phones_collection_web/views/phone_view.ex
defmodule PhonesCollectionWeb.PhoneView do
  use SiemensCollection.Web, :view

  def current_user(conn) do
    Addict.Helper.current_user(conn)
  end

  def is_logged_in(conn) do
    current_user(conn) != nil
  end

  def can_edit(conn) do
    PhonesCollectionWeb.Plugs.CheckAdminRights.can_edit(conn)
  end
end

lib/phones_collection_web/templates/phone/_edition.html.eex
<div class="edition">
  <h3 class="siemens-text">
    <%= @edition.name %>

    <%= if @edition.limited do %>
      <div class="btn btn-xs limited-label" title="Limited Edition">Limited</div>
    <% end %>

    <%= if @edition.prototype do %>
      <div class="btn btn-xs prototype-label" title="Prototype">Prototype</div>
    <% end %>

    <%= if @edition.id in @owned_edition_ids do %>
      <div class="btn btn-xs owned-label" title="Owned">Owned</div>
    <% end %>

    <%= if is_logged_in(@conn) do %>
      <%= link "Add to collection", to: Routes.catalog_item_path(@conn, :new, @brand.id, @phone.id, @edition), class: "btn btn-default btn-xs" %>
    <% end %>

    <%= if can_edit(@conn) do %>
      <%= link "Upload pics", to: Routes.catalog_picture_path(@conn, :new, @brand.id, @phone.id, @edition.id), class: "btn btn-default btn-xs" %>
      <%= link "Edit", to: Routes.catalog_phone_edition_path(@conn, :edit, @brand.id, @phone.id, @edition), class: "btn btn-default btn-xs" %>
      <%= if @edition.id != @phone.main_edition_id do %>
        <%= link "Set main", to: Routes.catalog_phone_path(@conn, :set_main_edition, @brand.id, @phone.id, @edition.id), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: Routes.catalog_phone_edition_path(@conn, :delete, @brand.id, @phone.id, @edition), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      <% end %>
    <% end %>
    </h3>
  <%= if length(@edition.pictures) > 0 do %>
    <div class="images">
      <%= for picture <- @edition.pictures do %>
        <% thumb_image_url = PhonesCollectionWeb.Picture.get_url(picture, :thumb) %>
        <% image_url = PhonesCollectionWeb.Picture.get_url(picture, :original) %>
        <a href="<%= image_url %>" target="_blank">
          <img src="<%= thumb_image_url %>"/>
        </a>
      <% end %>
    </div>
  <% end %>
  <div class="info">
    <ul>

      <%= for feature <- ~w(Release Limited Prototype Form_factor Network Weight Size Java LTE 3G Memory_card_support Memory_card_type IrDA Bluetooth GPRS Battery Notes) do %>
        <li>
          <% field = String.downcase(feature) |> String.to_atom %>
          <% %{^field => value} = @edition %>
          <strong><%= String.replace(feature, "_", " ") %>:</strong>
          <%= value %>
        </li>
      <% end %>

    </ul>
  </div>
</div>

lib/phones_collection_web/templates/phone/edit.html.eex
<div class='breadcrumbs'>
  <%= link "Brands >", to: Routes.brand_path(@conn, :index) %>
  <%= link "#{@brand.name} >", to: Routes.catalog_phone_path(@conn, :index, @brand.id) %>
  <%= link "#{@phone.name}", to: Routes.catalog_phone_path(@conn, :show, @brand.id, @phone) %>
  <%= "> Edit" %>
</div>

<h2>Edit</h2>

<%= render "form.html", changeset: @changeset,
                        brand: @brand,
                        brands: @brands,
                        series: @series,
                        action: Routes.catalog_phone_path(@conn, :update, @brand.id, @phone) %>

lib/phones_collection_web/templates/phone/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
  <%= hidden_input f, :brand_id, value: @brand.id %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <%= if @brands != nil do %>
    <div class="form-group">
      <%= label f, :brand_id, class: "control-label" %>
      <%= select f, :brand_id, [{"", nil} | Enum.map(@brands, fn s -> {s.name, s.id} end)] %>
      <%= error_tag f, :brand_id %>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :series_id, class: "control-label" %>
    <%= select f, :series_id, [{"", nil} | Enum.map(@series, fn s -> {s.name, s.id} end)] %>
    <%= error_tag f, :series_id %>
  </div>

  <div class="form-group">
    <%= label f, :notes, class: "control-label" %>
    <%= textarea f, :notes, class: "form-control" %>
    <%= error_tag f, :notes %>
  </div>

  <%= if @changeset.data.id == nil do %>
    <h3>Main edition</h3>
    <%= inputs_for f, :phone_editions, fn i -> %>

      <%= render PhonesCollectionWeb.PhoneEditionView, "_shared_inputs.html", form: i %>

    <% end %>

  <% end %>

  <div class="form-group">
    <%= if @changeset.data.id == nil do %>
      <%= submit "Create", class: "btn btn-primary" %>
      <%= submit "Create and Upload images", class: "btn btn-primary", name: "save_and_upload" %>
    <% else %>
      <%= submit "Update", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

lib/phones_collection_web/templates/phone/index.html.eex
<div class='breadcrumbs'>
  <%= link "Brands >", to: Routes.brand_path(@conn, :index) %>
  <%= @brand.name %>
</div>
<h2 class="siemens-text editions">
  <%= @brand.name %>
  <%= if can_edit(@conn) do %>
    <%= link "Edit brand", to: Routes.brand_path(@conn, :edit, @brand.id), class: "btn btn-default btn-xs" %>
    <%= link "Add phone", to: Routes.catalog_phone_path(@conn, :new, @brand.id), class: "btn btn-default btn-xs" %>
    <%= link "Add series", to: Routes.brand_series_path(@conn, :new, @brand.id), class: "btn btn-default btn-xs" %>
  <% end %>
</h2>

<%= if length(@phones_by_series) > 1 do %>
  <h4 class="siemens-text series-header">Series:</h4>
  <ul class="series-list">
    <%= for {[_, series_name], _} <- @phones_by_series do %>
      <li>
        <a href="#series-list-<%= if series_name != nil, do: Inflex.parameterize(series_name), else: "other" %>">
          <%= if series_name != nil, do: series_name, else: "Other" %></a>
      </li>
    <% end %>
  </ul>
<% end %>

<%= for {[series_id, series_name], phones} <- @phones_by_series do %>
  <%= if length(@phones_by_series) > 1 do %>
    <h4 class="siemens-text series-header" id="series-list-<%= if series_name != nil, do: Inflex.parameterize(series_name), else: "other" %>">
      <%= if series_name != nil do %>
        <%= series_name %>
        <%= if can_edit(@conn) do %>
          <%= link "Delete", to: Routes.brand_series_path(@conn, :delete, @brand.id, series_id), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
          <%= link "Edit", to: Routes.rand_series_path(@conn, :edit, @brand.id, series_id), class: "btn btn-default btn-xs" %>
        <% end %>
      <% else %>
        Other
      <% end %>
    </h4>
  <% end %>
  <div class="items-gallery">
    <%= for {phone, count} <- phones do %>
      <div class="items-gallery-item col-sm-3">
        <a href="<%= Routes.catalog_phone_path(@conn, :show, @brand.id, phone) %>" class="item-bg-link">
          <img src="<%= phone |> PhonesCollectionWeb.Phone.cover_image |> PhonesCollectionWeb.Picture.get_url(:thumb) %>">
        </a>
        <div class="title">
          <%= link "#{phone.name} (#{count})", to: Routes.catalog_phone_path(@conn, :show, @brand.id, phone) %>
          <td class="text-right">
            <%= if can_edit(@conn) do %>
              <%= link "Edit", to: Routes.catalog_phone_path(@conn, :edit, @brand.id, phone), class: "btn btn-default btn-xs" %>
              <%= link "Delete", to: Routes.catalog_phone_path(@conn, :delete, @brand.id, phone), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
            <% end %>
          </td>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

lib/phones_collection_web/templates/phone/new.html.eex
<div class='breadcrumbs'>
  <%= link "Brands >", to: Routes.brand_path(@conn, :index) %>
  <%= link "#{@brand.name}", to: Routes.catalog_phone_path(@conn, :index, @brand.id) %>
</div>

<h2>New phone</h2>

<%= render "form.html", changeset: @changeset,
                        brand: @brand,
                        brands: nil,
                        series: @series,
                        action: Routes.catalog_phone_path(@conn, :create, @brand.id) %>

lib/phones_collection_web/templates/phone/show.html.eex
<div class='breadcrumbs'>
  <%= link "Brands >", to: Routes.brand_path(@conn, :index) %>
  <%= link "#{@brand.name} >", to: Routes.catalog_phone_path(@conn, :index, @brand.id) %>
  <%= @phone.name %>
</div>

<div class="edition">
  <h2 class="phone siemens-text">
    <%= @phone.brand.name %> <%= @phone.name %>

    <%= render PhonesCollectionWeb.PhoneEditionView, "_labels_for_header.html", conn: @conn, phone_edition: @phone_edition %>

    <%= if is_logged_in(@conn) do %>
      <%= link "Add to collection", to: Routes.catalog_item_path(@conn, :new, @brand.id, @phone.id, @phone_edition), class: "btn btn-default btn-xs" %>
    <% end %>

    <%= if can_edit(@conn) do %>
      <%= link "Upload pics", to: Routes.catalog_picture_path(@conn, :new, @brand.id, @phone.id, @phone_edition.id), class: "btn btn-default btn-xs" %>
      <%= link "Edit edition", to: Routes.catalog_phone_edition_path(@conn, :edit, @brand.id, @phone.id, @phone_edition), class: "btn btn-default btn-xs" %>
      <%= if @phone_edition.id != @phone.main_edition_id do %>
        <%= link "Set main", to: Routes.catalog_phone_path(@conn, :set_main_edition, @brand.id, @phone.id, @phone_edition.id), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: Routes.catalog_phone_edition_path(@conn, :delete, @brand.id, @phone.id, @phone_edition), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      <% end %>
      <%= link "Edit phone", to: Routes.catalog_phone_path(@conn, :edit, @brand.id, @phone), class: "btn btn-default btn-xs" %>
      <%= link "New edition", to: Routes.catalog_phone_edition_path(@conn, :new, @brand.id, @phone.id), class: "btn btn-default btn-xs" %>
    <% end %>
  </h2>
  <%= render PhonesCollectionWeb.PhoneEditionView, "_show_edition.html", phone_edition: @phone_edition %>

  <%= if @phone.notes != nil && @phone.notes != "" do %>
    <h3 class="siemens-text">Description</h3>
    <p><%= @phone.notes %></p>
  <% end %>

  <%= if length(@editions) > 1 do %>
    <h3 class="siemens-text">Editions</h3>

    <div class="items-gallery">
      <%= for edition <- @editions do %>
        <div class="items-gallery-item col-sm-3">
          <%= link to: Routes.catalog_phone_edition_path(@conn, :show, @brand.id, @phone.id, edition), class: "item-bg-link" do %>
            <img src="<%= PhonesCollectionWeb.Picture.cover(edition) |> PhonesCollectionWeb.Picture.get_url(:thumb) %>">
          <% end %>
          <div class="title">
            <%= link PhonesCollectionWeb.PhoneEditionView.phone_name(edition) <> PhonesCollectionWeb.PhoneEditionView.full_edition_name(edition, false), to: Routes.catalog_phone_edition_path(@conn, :show, @brand.id, @phone.id, edition) %>
            <%= if can_edit(@conn) && edition.id == @phone.main_edition_id do %>
              (Main)
            <% end %>
            <%= if edition.limited do %><span title="Limited Edition" class="limited-label round-label">L</span><% end %>
            <%= if edition.prototype do %><span title="Prototype" class="prototype-label round-label">P</span><% end %>
            <%= if edition.operator_edition do %>
              <span title="Operator's edition: <%= edition.operator_name %>" class="operator-label round-label">O</span>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

</div>