lib/phones_collection_web/router.ex
defmodule PhonesCollectionWeb.Router do
  use SiemensCollection.Web, :router
  use Addict.RoutesHelper

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    addict :routes
  end

  scope "/", PhonesCollectionWeb do
    pipe_through :browser

    scope "/profile" do
      get "/", ProfileController, :edit
      put "/", ProfileController, :update
      delete "/:id", ProfileController, :delete
    end
    scope "/deals", assigns: %{filter: "successful"} do
      get "/successful", DealController, :index, as: :successful_deal
    end
    scope "/deals", assigns: %{filter: "all"} do
      get "/all", DealController, :index, as: :all_deal
    end
    scope "/deals", assigns: %{filter: "failed"} do
      get "/failed", DealController, :index, as: :failed_deal
    end
    resources "/deals", DealController
    get "/deals/:deal_id/item", ItemController, :new

    scope "/collections", as: :collections do
      get "/", CollectionController, :index
      scope "/:user_id" do
        resources "/", ItemController
        scope "/:item_id/images" do
          get "/new", PictureController, :new
          post "/", PictureController, :create
          delete "/:id", PictureController, :delete
          post "/:id/rotate/:direction", PictureController, :rotate
          put "/:id/set_cover", PictureController, :set_cover
        end
      end
    end

    resources "/", BrandController, except: [:show] do
      resources "/series", SeriesController, except: [:index, :show]
    end

    scope "/:brand_id", as: :catalog do
      resources "/", PhoneController
      scope "/:phone_id" do
        resources "/", PhoneEditionController, except: [:index]
        get "/:edition_id/set_main", PhoneController, :set_main_edition
        get "/:edition_id/add_to_collection", ItemController, :new
        scope "/:edition_id/images" do
          get "/new", PictureController, :new
          post "/", PictureController, :create
          delete "/:id", PictureController, :delete
          post "/:id/rotate/:direction", PictureController, :rotate
          put "/:id/set_cover", PictureController, :set_cover
        end
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SiemensCollection do
  #   pipe_through :api
  # end
end

lib/phones_collection_web/controllers/deal_controller.ex
defmodule PhonesCollectionWeb.DealController do
  use SiemensCollection.Web, :controller

  alias PhonesCollectionWeb.{Deal, PhoneEdition, User}

  plug :set_deal when action in [:show, :edit, :update, :delete]

  # plug Addict.Plugs.Authenticated when action in [:index, :new, :create]
  plug :check_rights when action in [:show, :edit, :update, :delete]

  plug :scrub_params, "deal" when action in [:create, :update]
  plug :set_user

  def index(conn, _params) do
    user_id = conn.assigns.user.id
    query = Deal |> Deal.for_user(user_id)
    query = case conn.assigns[:filter] do
      "successful" ->
        Deal.successful(query)
      "failed" ->
        Deal.failed(query)
      "all" ->
        query
      _ ->
        Deal.in_progress(query)
    end
    query = from query, preload: [phone_edition: [phone: :brand]]

    deals = Repo.all(query)

    render(conn, "index.html", deals: deals)
  end

  def new(conn, _params) do
    hash = if conn.params["edition_id"] do
      %Deal{phone_edition_id: conn.params["edition_id"]}
    else
      %Deal{}
    end
    changeset = Deal.changeset(hash)
    phone_editions = preload_editions
    render(conn, "new.html", phone_editions: phone_editions, changeset: changeset)
  end

  def create(conn, %{"deal" => deal_params}) do
    params = Map.merge(deal_params, %{"user_id" => Addict.Helper.current_user(conn).id})
    changeset = Deal.changeset(%Deal{}, params)

    case Repo.insert(changeset) do
      {:ok, deal} ->
        conn
        |> put_flash(:info, "Deal created successfully.")
        |> redirect(to: Routes.deal_path(conn, :show, deal.id))
      {:error, changeset} ->
        phone_editions = preload_editions
        render(conn, "new.html", phone_editions: phone_editions, changeset: changeset)
    end
  end

  def show(conn, _params) do
    deal = conn.assigns.deal |> Repo.preload([:item, phone_edition: [phone: :brand]])
    render(conn, "show.html", deal: deal)
  end

  def edit(conn, _params) do
    deal = conn.assigns.deal |> Repo.preload([phone_edition: [phone: :brand]])
    phone_editions = preload_editions
    changeset = Deal.changeset(deal)
    render(conn, "edit.html", deal: deal, phone_editions: phone_editions, changeset: changeset)
  end

  def update(conn, %{"deal" => deal_params}) do
    deal = conn.assigns.deal |> Repo.preload([phone_edition: [phone: :brand]])
    changeset = Deal.changeset(deal, deal_params)

    case Repo.update(changeset) do
      {:ok, deal} ->
        conn
        |> put_flash(:info, "Deal updated successfully.")
        |> redirect(to: Routes.deal_path(conn, :show, deal))
      {:error, changeset} ->
        phone_editions = preload_editions
        render(conn, "edit.html", deal: deal, phone_editions: phone_editions, changeset: changeset)
    end
  end

  def delete(conn, _params) do
    deal = conn.assigns.deal

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(deal)

    conn
    |> put_flash(:info, "Deal deleted successfully.")
    |> redirect(to: Routes.deal_path(conn, :index))
  end

  defp set_user(conn, _) do
    user = Repo.get(User, Addict.Helper.current_user(conn).id)
    assign(conn, :user, user)
  end

  defp set_deal(conn, _) do
    deal = Repo.get!(Deal, conn.params["id"])
    assign(conn, :deal, deal)
  end

  def check_rights(conn, _opts) do
    if Addict.Helper.current_user(conn) != nil && Addict.Helper.current_user(conn).id == conn.assigns.deal.user_id do
      conn
    else
      conn
      |> put_flash(:info, "You have no rights to do it")
      |> redirect(to: Routes.brand_path(conn, :index))
    end
  end

  defp preload_editions do
    Repo.all(PhoneEdition)
    |> Repo.preload([phone: :brand])
    |> Enum.sort_by(&("#{PhonesCollectionWeb.PhoneEditionView.full_phone_name(&1)}"))
  end

end

lib/phones_collection_web/views/deal_view.ex
defmodule PhonesCollectionWeb.DealView do
  use SiemensCollection.Web, :view

  def current_user_id(conn) do
    if Addict.Helper.current_user(conn) do
      Addict.Helper.current_user(conn).id
    else
      nil
    end
  end

  def link_or_text(text, filter, value, link) when filter != value do
    link text, to: link
  end

  def link_or_text(text, filter, value, link) do
    text
  end
end

lib/phones_collection_web/templates/deal/edit.html.eex
<div class='breadcrumbs'>
  <%= link "Deals >", to: Routes.deal_path(@conn, :index) %>
  <%= link PhonesCollectionWeb.PhoneEditionView.full_phone_name(@deal.phone_edition), to: Routes.deal_path(@conn, :show, @deal) %>
  <%= "> Edit" %>
</div>

<%= render "form.html", changeset: @changeset,
                        phone_editions: @phone_editions,
                        action: Routes.deal_path(@conn, :update, @deal) %>

lib/phones_collection_web/templates/deal/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :phone_edition_id, class: "control-label" %>
    <%= select f, :phone_edition_id, 
      Enum.map(@phone_editions, fn p -> {PhonesCollectionWeb.PhoneEditionView.full_phone_name(p), p.id} end) %>
    <%= error_tag f, :phone_edition_id %>
  </div>

  <div class="form-group">
    <%= label f, :status, class: "control-label" %>
    <%= select f, :status, Enum.map(["Just noticed", "Waiting for answer", "In progress", "Delivery", "Success", "Failed"], &({&1,&1})) %>
    <%= error_tag f, :status %>
  </div>

  <%= for feature <- ~w(Link From Contact_name Contact_email Contact_phone Price) do %>

    <div class="form-group">
      <% field = String.downcase(feature) |> String.to_atom %>
      <%= label f, field, class: "control-label" %>:
      <%= text_input f, field, class: "form-control" %>
      <%= if message = f.errors[field] do %>
        <span class="help-block"><%= message %></span>
      <% end %>
    </div>
    
  <% end %>

  <div class="form-group">
    <%= label f, :notes, class: "control-label" %>
    <%= textarea f, :notes, class: "form-control" %>
    <%= error_tag f, :notes %>
  </div>

  <div class="form-group">
    <%= submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

lib/phones_collection_web/templates/deal/index.html.eex
<div class='breadcrumbs'>
  Deals >
</div>

<h2 class="siemens-text editions">
  Deals Manager
  <%= link "New deal", to: Routes.deal_path(@conn, :new), class: "btn btn-default btn-xs" %>
</h2>

<%= link_or_text "In progress", nil, @conn.assigns[:filter], Routes.deal_path(@conn, :index) %> |
<%= link_or_text "Successful", "successful", @conn.assigns[:filter], Routes.successful_deal_path(@conn, :index) %> |
<%= link_or_text "Failed", "failed", @conn.assigns[:filter], Routes.failed_deal_path(@conn, :index) %> |
<%= link_or_text "All", "all", @conn.assigns[:filter], Routes.all_deal_path(@conn, :index) %>

<table class="table">
  <thead>
    <tr>
      <th>Phone</th>
      <th>Last update</th>
      <th>From</th>
      <th>Status</th>
      <th>Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= for deal <- @deals do %>
      <tr>
        <td><%= link PhonesCollectionWeb.PhoneEditionView.full_phone_name(deal.phone_edition), to: Routes.deal_path(@conn, :show, deal) %></td>
        <td><%= deal.updated_at |> DateTime.to_iso8601 %></td>
        <td><%= deal.from %></td>
        <td><%= deal.status %></td>
        <td><%= deal.price %></td>
        <td class="text-right">
          <%= link "Edit", to: Routes.deal_path(@conn, :edit, deal.id), class: "btn btn-default btn-xs" %>
          <%= link "Delete", to: Routes.deal_path(@conn, :delete, deal.id), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
        </td>
      <tr>
    <% end %>
  </tbody>
</table>

lib/phones_collection_web/templates/deal/new.html.eex
<div class='breadcrumbs'>
  <%= link "Deals >", to: Routes.deal_path(@conn, :index) %>
  <%= "Add new deal" %>
</div>

<%= render "form.html", changeset: @changeset,
                        phone_editions: @phone_editions,
                        action: Routes.deal_path(@conn, :create) %>

lib/phones_collection_web/templates/deal/show.html.eex
<div class='breadcrumbs'>
  <%= link "Deals >", to: Routes.deal_path(@conn, :index) %>
  <%= "#{PhonesCollectionWeb.PhoneEditionView.full_phone_name(@deal.phone_edition)}" %>
</div>

<h2 class="siemens-text phone">
  <%= PhonesCollectionWeb.PhoneEditionView.full_phone_name(@deal.phone_edition) %>
  <%= if @deal.phone_edition.limited do %><span title="Limited Edition" class="btn btn-xs ed-label limited-label">Limited</span><% end %>
  <%= if @deal.phone_edition.prototype do %><span title="Prototype" class="btn btn-xs ed-label prototype-label">Prototype</span><% end %>
  <%= if @deal.phone_edition.operator_edition do %>
    <div class="btn btn-xs ed-label operator-label" title="Operator's edition: <%= @deal.phone_edition.operator_name %>">
      Operator
    </div>
  <% end %>

  <%= link "Open in catalog", to: Routes.catalog_phone_edition_path(@conn, :show, @deal.phone_edition.phone.brand.id, @deal.phone_edition.phone, @deal.phone_edition), class: "btn btn-default btn-xs" %>
  <%= if @deal.item == nil do %>
    <%= link "Add to collection", to: Routes.item_path(@conn, :new, @deal), class: "btn btn-default btn-xs" %>
  <% else %>
    <%= link "Open in collection", to: Routes.collections_item_path(@conn, :show, current_user_id(@conn), @deal.item), class: "btn btn-default btn-xs" %>
  <% end %>
  <%= link "Edit", to: Routes.deal_path(@conn, :edit, @deal), class: "btn btn-default btn-xs" %>
</h2>

<ul class="deal">

  <li>
    <strong>Status:</strong>
    <%= @deal.status %>
  </li>

  <li>
    <strong>Link:</strong>
    <%= link @deal.link, to: @deal.link %>
  </li>

  <li>
    <strong>From:</strong>
    <%= @deal.from %>
  </li>

  <li>
    <strong>Contact name:</strong>
    <%= @deal.contact_name %>
  </li>

  <li>
    <strong>Contact email:</strong>
    <%= @deal.contact_email %>
  </li>

  <li>
    <strong>Contact phone:</strong>
    <%= @deal.contact_phone %>
  </li>

  <li>
    <strong>Price:</strong>
    <%= @deal.price %>
  </li>

  <li>
    <strong>Created at:</strong>
    <%= @deal.inserted_at |> DateTime.to_iso8601 %>
  </li>

  <li>
    <strong>Updated at:</strong>
    <%= @deal.updated_at |> DateTime.to_iso8601 %>
  </li>

  <li>
    <strong>Notes:</strong>
    <%= @deal.notes %>
  </li>

</ul>