lib/phones_collection_web/router.ex
defmodule PhonesCollectionWeb.Router do
  use SiemensCollection.Web, :router
  use Addict.RoutesHelper

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    addict :routes
  end

  scope "/", PhonesCollectionWeb do
    pipe_through :browser

    scope "/profile" do
      get "/", ProfileController, :edit
      put "/", ProfileController, :update
      delete "/:id", ProfileController, :delete
    end
    scope "/deals", assigns: %{filter: "successful"} do
      get "/successful", DealController, :index, as: :successful_deal
    end
    scope "/deals", assigns: %{filter: "all"} do
      get "/all", DealController, :index, as: :all_deal
    end
    scope "/deals", assigns: %{filter: "failed"} do
      get "/failed", DealController, :index, as: :failed_deal
    end
    resources "/deals", DealController
    get "/deals/:deal_id/item", ItemController, :new

    scope "/collections", as: :collections do
      get "/", CollectionController, :index
      scope "/:user_id" do
        resources "/", ItemController
        scope "/:item_id/images" do
          get "/new", PictureController, :new
          post "/", PictureController, :create
          delete "/:id", PictureController, :delete
          post "/:id/rotate/:direction", PictureController, :rotate
          put "/:id/set_cover", PictureController, :set_cover
        end
      end
    end

    resources "/", BrandController, except: [:show] do
      resources "/series", SeriesController, except: [:index, :show]
    end

    scope "/:brand_id", as: :catalog do
      resources "/", PhoneController
      scope "/:phone_id" do
        resources "/", PhoneEditionController, except: [:index]
        get "/:edition_id/set_main", PhoneController, :set_main_edition
        get "/:edition_id/add_to_collection", ItemController, :new
        scope "/:edition_id/images" do
          get "/new", PictureController, :new
          post "/", PictureController, :create
          delete "/:id", PictureController, :delete
          post "/:id/rotate/:direction", PictureController, :rotate
          put "/:id/set_cover", PictureController, :set_cover
        end
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SiemensCollection do
  #   pipe_through :api
  # end
end

lib/phones_collection_web/views/layout_view.ex
defmodule PhonesCollectionWeb.LayoutView do
  use SiemensCollection.Web, :view

  def current_user(conn) do
    Addict.Helper.current_user(conn)
  end

  def is_logged_in(conn) do
    current_user(conn) != nil
  end

  def can_edit(conn) do
    PhonesCollectionWeb.Plugs.CheckAdminRights.can_edit(conn)
  end

  def csrf_token(conn) do
    Phoenix.Controller.get_csrf_token
  end
end

lib/phones_collection_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Phones Collection</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <input type="hidden" id="csrf-token" value="<%= csrf_token(@conn) %>"/>
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right login-line">
            <%= if is_logged_in(@conn) do %>
              <li><%= link "/ Deals", to: Routes.deal_path(@conn, :index) %></li>
              <li><%= link "/ My", to: Routes.collections_item_path(@conn, :index, current_user(@conn).id) %></li>
              <li><a id="btn-logout">/ Logout</a></li>
            <% else %>
              <li><a href="/login">/ Login</a></li>
            <% end %>
          </ul>
        </nav>
        <span class="logo"><a href="/"><h2>Phones Collection</h2></a></span>
        <nav role="navigation">
          <ul class="nav menu-line">
              <li><%= link "Database /", to: Routes.brand_path(@conn, :index) %></li>
              <li><%= link "Collections /", to: Routes.collections_collection_path(@conn, :index) %></li>
          </ul>
        </nav>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= Routes.static_path(@conn, "/js/vendor.js") %>"></script>
    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>