lib/phones_collection_web/router.ex
defmodule PhonesCollectionWeb.Router do
  use SiemensCollection.Web, :router
  use Addict.RoutesHelper

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    addict :routes
  end

  scope "/", PhonesCollectionWeb do
    pipe_through :browser

    scope "/profile" do
      get "/", ProfileController, :edit
      put "/", ProfileController, :update
      delete "/:id", ProfileController, :delete
    end
    scope "/deals", assigns: %{filter: "successful"} do
      get "/successful", DealController, :index, as: :successful_deal
    end
    scope "/deals", assigns: %{filter: "all"} do
      get "/all", DealController, :index, as: :all_deal
    end
    scope "/deals", assigns: %{filter: "failed"} do
      get "/failed", DealController, :index, as: :failed_deal
    end
    resources "/deals", DealController
    get "/deals/:deal_id/item", ItemController, :new

    scope "/collections", as: :collections do
      get "/", CollectionController, :index
      scope "/:user_id" do
        resources "/", ItemController
        scope "/:item_id/images" do
          get "/new", PictureController, :new
          post "/", PictureController, :create
          delete "/:id", PictureController, :delete
          post "/:id/rotate/:direction", PictureController, :rotate
          put "/:id/set_cover", PictureController, :set_cover
        end
      end
    end

    resources "/", BrandController, except: [:show] do
      resources "/series", SeriesController, except: [:index, :show]
    end

    scope "/:brand_id", as: :catalog do
      resources "/", PhoneController
      scope "/:phone_id" do
        resources "/", PhoneEditionController, except: [:index]
        get "/:edition_id/set_main", PhoneController, :set_main_edition
        get "/:edition_id/add_to_collection", ItemController, :new
        scope "/:edition_id/images" do
          get "/new", PictureController, :new
          post "/", PictureController, :create
          delete "/:id", PictureController, :delete
          post "/:id/rotate/:direction", PictureController, :rotate
          put "/:id/set_cover", PictureController, :set_cover
        end
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", SiemensCollection do
  #   pipe_through :api
  # end
end

lib/phones_collection_web/controllers/item_controller.ex
defmodule PhonesCollectionWeb.ItemController do
  use SiemensCollection.Web, :controller

  alias PhonesCollectionWeb.{Item, PhoneEdition, User}

  # plug Addict.Plugs.Authenticated when action in [:new, :create]

  plug :scrub_params, "item" when action in [:create, :update]
  plug :set_user
  plug :set_item when action in [:show, :edit, :update, :delete]

  plug :check_rights when action in [:edit, :update, :delete]

  def index(conn, _params) do
    user_id = conn.assigns.user.id
    query = Item |> Item.for_user(user_id) |> Item.pictures_count
    query = from query, preload: [:pictures, :cover, phone_edition: [:pictures, :cover, phone: :brand]]

    items = Repo.all(query)

    render(conn, "index.html", items: items)
  end

  def new(conn, _params) do
    hash = cond do
      conn.params["edition_id"] ->
        %Item{user_id: Addict.Helper.current_user(conn).id, phone_edition_id: conn.params["edition_id"]}
      conn.params["deal_id"] ->
        deal = Repo.get!(PhonesCollectionWeb.Deal, conn.params["deal_id"])
        %Item{user_id: Addict.Helper.current_user(conn).id, deal_id: deal.id, phone_edition_id: deal.phone_edition_id}
      true ->
        %Item{user_id: Addict.Helper.current_user(conn).id}
    end
    changeset = Item.changeset(hash)
    phone_editions = preload_editions
    render(conn, "new.html", phone_editions: phone_editions, changeset: changeset)
  end

  def create(conn, %{"item" => item_params}) do
    params = Map.merge(item_params, %{"user_id" => Addict.Helper.current_user(conn).id})
    changeset = Item.changeset(%Item{}, params)

    case Repo.insert(changeset) do
      {:ok, item} ->
        redirect_path = if conn.params["save_and_upload"] != nil do
          Routes.collections_picture_path(conn, :new, conn.assigns.user.id, item.id)
        else
          Routes.collections_item_path(conn, :show, conn.assigns.user.id, item.id)
        end
        conn
        |> put_flash(:info, "Item created successfully.")
        |> redirect(to: redirect_path)
      {:error, changeset} ->
        phone_editions = preload_editions
        render(conn, "new.html", phone_editions: phone_editions, changeset: changeset)
    end
  end

  def show(conn, _params) do
    item = conn.assigns.item |> Repo.preload([:pictures, :cover, phone_edition: [:pictures, :cover, phone: :brand]])
    render(conn, "show.html", item: item)
  end

  def edit(conn, _params) do
    item = conn.assigns.item |> Repo.preload([:pictures, phone_edition: [:pictures, phone: :brand]])
    phone_editions = preload_editions
    changeset = Item.changeset(item)
    render(conn, "edit.html", item: item, phone_editions: phone_editions, changeset: changeset)
  end

  def update(conn, %{"item" => item_params}) do
    item = conn.assigns.item
    changeset = Item.changeset(item, item_params)

    case Repo.update(changeset) do
      {:ok, item} ->
        conn
        |> put_flash(:info, "Item updated successfully.")
        |> redirect(to: Routes.collections_item_path(conn, :show, conn.assigns.user.id, item))
      {:error, changeset} ->
        phone_editions = preload_editions
        render(conn, "edit.html", item: item, phone_editions: phone_editions, changeset: changeset)
    end
  end

  def delete(conn, _params) do
    item = conn.assigns.item

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(item)

    conn
    |> put_flash(:info, "Item deleted successfully.")
    |> redirect(to: Routes.ollections_item_path(conn, :index, conn.assigns.user.id))
  end

  defp set_user(conn, _) do
    user = if conn.params["user_id"] do
             Repo.get(User, conn.params["user_id"])
           else
             Repo.get(User, Addict.Helper.current_user(conn).id)
           end
    assign(conn, :user, user)
  end

  defp set_item(conn, _) do
    item = Repo.get!(Item, conn.params["id"])
    assign(conn, :item, item)
  end

  def check_rights(conn, _opts) do
    if Addict.Helper.current_user(conn) != nil && Addict.Helper.current_user(conn).id == conn.assigns.item.user_id do
      conn
    else
      conn
      |> put_flash(:info, "You have no rights to do it")
      |> redirect(to: Routes.brand_path(conn, :index))
    end
  end

  defp preload_editions do
    Repo.all(PhoneEdition)
    |> Repo.preload([phone: :brand])
    |> Enum.sort_by(&("#{PhonesCollectionWeb.PhoneEditionView.full_phone_name(&1)}"))
  end

end

lib/phones_collection_web/views/item_view.ex
defmodule PhonesCollectionWeb.ItemView do
  use SiemensCollection.Web, :view

  def can_edit_admin(conn, user) do
    PhonesCollectionWeb.Plugs.CheckAdminRights.can_edit_user(conn, user)
  end

  def can_edit(conn, item) do
    current_user_id(conn) == item.user_id
  end

  def can_edit_user(conn, user) do
    current_user_id(conn) == user.id
  end

  def current_user_id(conn) do
    if Addict.Helper.current_user(conn) do
      Addict.Helper.current_user(conn).id
    else
      nil
    end
  end
end

lib/phones_collection_web/templates/item/_features_list.html.eex
<ul>
  <li>
    <strong>Condition:</strong>
    <%= @item.condition %>
  </li>

  <%= if @item.released != nil && @item.released != "" do %>
    <li>
      <strong>Released:</strong>
      <%= @item.released %>
    </li>
  <% end %>

  <%= if @item.imei != nil && @item.imei != "" do %>
    <li>
      <strong>Imei:</strong>
      <%= @item.imei %>
    </li>
  <% end %>

  <%= if @item.sw != nil && @item.sw != "" do %>
    <li>
      <strong>Sw:</strong>
      <%= @item.sw %>
    </li>
  <% end %>

  <%= if @item.calls_time != nil && @item.calls_time != "" do %>
  <li>
    <strong>Calls time:</strong>
    <%= @item.calls_time %>
  </li>
  <% end %>

  <%= if @item.set != nil && @item.set != "" do %>
  <li>
    <strong>Set:</strong>
    <%= @item.set %>
  </li>
  <% end %>

  <li>
    <strong>Want to sell:</strong><%= if @item.selling do %>
          Yes
        <% else %>
          No
        <% end %>
  </li>

  <%= if @item.deal_id != nil && can_edit(@conn, @item) do %>
    <li>
      <strong>Deal info:</strong>
      <%= link "Show", to: Routes.deal_path(@conn, :show, @item.deal_id) %>
    </li>
  <% end %>

</ul>

lib/phones_collection_web/templates/item/_show_item.html.eex
<div class="row phone-info-block">
  <%= if @item.cover_id != nil do %>
    <div class="images cover col-sm-4" id="lightgallery-cover">
      <% thumb_image_url = PhonesCollectionWeb.Picture.get_url(@item.cover, :thumb) %>
      <% lightbox_image_url = PhonesCollectionWeb.Picture.get_url(@item.cover, :popup) %>
      <% image_url = PhonesCollectionWeb.Picture.get_url(@item.cover) %>
      <a href="<%= lightbox_image_url %>" data-download-url="<%= image_url %>">
        <img src="<%= thumb_image_url %>" class="thumb"/>
      </a>
    </div>
  <% end %>
  <div class="info col-sm-8">
    <%= render "_features_list.html", conn: @conn, item: @item %>
  </div>
</div>

lib/phones_collection_web/templates/item/edit.html.eex
<div class='breadcrumbs'>
  <%= link "Collections >", to: Routes.collections_collection_path(@conn, :index) %>
  <%= link "#{@user.name} >", to: Routes.collections_item_path(@conn, :index, @user) %>
  <%= link PhonesCollectionWeb.PhoneEditionView.full_phone_name(@item.phone_edition),
           to: Routes.collections_item_path(@conn, :show, @user, @item) %>
  <%= "> Edit" %>
</div>

<%= render "form.html", changeset: @changeset,
                        phone_editions: @phone_editions,
                        action: Routes.collections_item_path(@conn, :update, @user, @item) %>

<h2>Images</h2>

<%= link "Upload new images", to: Routes.collections_picture_path(@conn, :new, @user, @item.id) %>
<br><br>
<%= if length(@item.pictures) > 0 do %>
  <div class="edit_images">
    <%= for picture <- @item.pictures do %>
      <% thumb_image_url = PhonesCollectionWeb.Picture.get_url(picture, :thumb) %>
      <% image_url = PhonesCollectionWeb.Picture.get_url(picture) %>
      <div class="image">
        <a href="<%= image_url %>" target="_blank">
          <img src="<%= thumb_image_url %>"/>
        </a>
        <%= link "Destroy", to: Routes.collections_picture_path(@conn, :delete, @user, @item.id, picture.id), method: :delete %>
        <%= link "Rotate ↻", to: Routes.collections_picture_path(@conn, :rotate, @user, @item.id, picture.id, "right"), method: :post %>
        <%= link "Rotate ↺", to: Routes.collections_picture_path(@conn, :rotate, @user, @item.id, picture.id, "left"), method: :post %>
        <%= if picture.id != @item.cover_id do %>
          <%= link "Set cover", to: Routes.collections_picture_path(@conn, :set_cover, @user, @item.id, picture.id), method: :put %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

lib/phones_collection_web/templates/item/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= hidden_input f, :deal_id, class: "form-control" %>

  <div class="form-group">
    <%= label f, :phone_edition_id, class: "control-label" %>
    <%= select f, :phone_edition_id,
      Enum.map(@phone_editions, fn p -> {PhonesCollectionWeb.PhoneEditionView.full_phone_name(p), p.id} end) %>
    <%= error_tag f, :phone_edition_id %>
  </div>

  <div class="form-group">
    <%= label f, :notes, class: "control-label" %>
    <%= textarea f, :notes, class: "form-control" %>
    <%= error_tag f, :notes %>
  </div>

  <div class="form-group">
    <%= label f, :condition, class: "control-label" %>
    <%= select f, :condition, 1..10 %>
    <%= error_tag f, :condition %>
  </div>

  <div class="form-group">
    <%= label f, :released, class: "control-label" %>
    <%= text_input f, :released, class: "form-control" %>
    <%= error_tag f, :released %>
  </div>

  <div class="form-group">
    <%= label f, :imei, class: "control-label" %>
    <%= text_input f, :imei, class: "form-control" %>
    <%= error_tag f, :imei %>
  </div>

  <div class="form-group">
    <%= label f, :sw, class: "control-label" %>
    <%= text_input f, :sw, class: "form-control" %>
    <%= error_tag f, :sw %>
  </div>

  <div class="form-group">
    <%= label f, :calls_time, class: "control-label" %>
    <%= text_input f, :calls_time, class: "form-control" %>
    <%= error_tag f, :calls_time %>
  </div>

  <div class="form-group">
    <%= label f, :set, class: "control-label" %>
    <%= textarea f, :set, class: "form-control" %>
    <%= error_tag f, :set %>
  </div>

  <div class="form-group">
    <%= label f, :full_set, "Complete set", class: "control-label" %>:
    <%= checkbox f, :full_set %>
    <%= error_tag f, :full_set %>
  </div>

  <div class="form-group">
    <%= label f, :selling, "Want to sell", class: "control-label" %>:
    <%= checkbox f, :selling %>
    <%= error_tag f, :selling %>
  </div>

  <div class="form-group">
    <%= if @changeset.data.id == nil do %>
      <%= submit "Create", class: "btn btn-primary" %>
      <%= submit "Create and Upload images", class: "btn btn-primary", name: "save_and_upload" %>
    <% else %>
      <%= submit "Update", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

lib/phones_collection_web/templates/item/index.html.eex
<div class='breadcrumbs'>
  <%= link "Collections >", to: Routes.collections_collection_path(@conn, :index) %>
  <%= @user.name %>
</div>

<h2 class="siemens-text editions">
  <%= @user.name %>
  <%= if can_edit_user(@conn, @user) do %>
    <%= link "Edit", to: Routes.profile_path(@conn, :edit), class: "btn btn-default btn-xs" %>
  <% end %>
  <%= if can_edit_admin(@conn, @user) do %>
    <%= link "Delete", to: Routes.profile_path(@conn, :delete, @user.id), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
  <% end %>
</h2>
<p><%= @user.location %></p>
<p><%= @user.description %></p>

<h3 class="siemens-text collection">
  Collection
  <%= if can_edit_user(@conn, @user) do %>
    <%= link "New item", to: Routes.collections_item_path(@conn, :new, @user), class: "btn btn-default btn-xs" %>
  <% end %>
</h3>
<div class="items-gallery">
  <%= for {item, count} <- @items do %>
    <div class="items-gallery-item col-sm-3">
      <a href="<%= Routes.collections_item_path(@conn, :show, @user, item) %>" class="item-bg-link">
        <img src="<%= item |> PhonesCollectionWeb.Item.cover_image |> PhonesCollectionWeb.Picture.get_url(:thumb) %>">
      </a>
      <div class="title">
        <a href="<%= Routes.collections_item_path(@conn, :show, @user, item) %>">
          <%= raw PhonesCollectionWeb.PhoneEditionView.full_phone_name(item.phone_edition, true, "<br>") %>
        </a>
        <%= if count > 0 do %>[<%= count %>📷]<% end %>
        <%= if item.phone_edition.limited do %><span title="Limited Edition" class="limited-label round-label">L</span><% end %>
        <%= if item.phone_edition.prototype do %><span title="Prototype" class="prototype-label round-label">P</span><% end %>
        <%= if item.full_set do %><span title="Full set" class="fullset-label round-label">S</span><% end %>

        <td class="text-right">
          <%= if can_edit(@conn, item) do %>
            <%= link "Edit", to: Routes.collections_item_path(@conn, :edit, @user, item), class: "btn btn-default btn-xs" %>
            <%= link "X", to: Routes.collections_item_path(@conn, :delete, @user, item), method: :delete, data: [confirm: "Are you sure you want to delete this item from collection?"], class: "btn btn-danger btn-xs" %>
          <% end %>
        </td>
      </div>
    </div>
  <% end %>
</div>

lib/phones_collection_web/templates/item/new.html.eex
<div class='breadcrumbs'>
  <%= link "Collections >", to: Routes.collections_collection_path(@conn, :index) %>
  <%= link "#{@user.name} >", to: Routes.collections_item_path(@conn, :index, @user) %>
  <%= "Add to collection" %>
</div>

<%= render "form.html", changeset: @changeset,
                        phone_editions: @phone_editions,
                        action: Routes.collections_item_path(@conn, :create, @user) %>

lib/phones_collection_web/templates/item/show.html.eex
<div class='breadcrumbs'>
  <%= link "Collections >", to: Routes.collections_collection_path(@conn, :index) %>
  <%= link "#{@user.name} >", to: Routes.collections_item_path(@conn, :index, @user) %>
  <%= "#{PhonesCollectionWeb.PhoneEditionView.full_phone_name(@item.phone_edition)}" %>
</div>

<h2 class="siemens-text phone">
  <%= PhonesCollectionWeb.PhoneEditionView.full_phone_name(@item.phone_edition) %>
  <%= if @item.phone_edition.limited do %><span title="Limited Edition" class="btn btn-xs ed-label limited-label">Limited</span><% end %>
  <%= if @item.phone_edition.prototype do %><span title="Prototype" class="btn btn-xs ed-label prototype-label">Prototype</span><% end %>
  <%= if @item.phone_edition.operator_edition do %>
    <div class="btn btn-xs ed-label operator-label" title="Operator's edition: <%= @item.phone_edition.operator_name %>">
      Operator
    </div>
  <% end %>
  <%= if @item.full_set do %><span title="Full set" class="btn btn-xs ed-label owned-label">Full set</span><% end %>
  <%= link "Open in catalog", to: Routes.catalog_phone_edition_path(@conn, :show, @item.phone_edition.phone.brand.id, @item.phone_edition.phone, @item.phone_edition), class: "btn btn-default btn-xs" %>
  <%= if can_edit(@conn, @item) do %>
    <%= link "Edit", to: Routes.collections_item_path(@conn, :edit, @user, @item), class: "btn btn-default btn-xs" %>
    <%= link "Upload pics", to: Routes.collections_picture_path(@conn, :new, @user, @item.id), class: "btn btn-default btn-xs" %>
  <% end %>
</h2>

<%= render "_show_item.html", conn: @conn, item: @item %>

<%= if @item.notes != nil && @item.notes != "" do %>
  <h2 class="siemens-text">Notes</h2>
  <p><%= @item.notes %></p>
<% end %>

<h2 class="siemens-text editions">All Images</h2>
<%= if length(@item.pictures) > 0 do %>
  <div class="images" id="lightgallery">
    <%= for picture <- (Enum.sort(@item.pictures, &(&2.id != nil && @item.cover_id == &1.id))) do %>
      <% thumb_image_url = PhonesCollectionWeb.Picture.get_url(picture, :thumb) %>
      <% lightbox_image_url = PhonesCollectionWeb.Picture.get_url(picture, :popup) %>
      <% image_url = PhonesCollectionWeb.Picture.get_url(picture) %>
      <a href="<%= lightbox_image_url %>" data-download-url="<%= image_url %>">
        <img src="<%= thumb_image_url %>" class="thumb"/>
      </a>
    <% end %>
  </div>
<% else %>
  <%= if length(@item.phone_edition.pictures) > 0 do %>
    These pictures are from the database:<br><br>
    <div class="images" id="lightgallery">
      <%= for picture <- (Enum.sort(@item.phone_edition.pictures, &(&2.id != nil && @item.phone_edition.cover_id == &1.id))) do %>
        <% thumb_image_url = PhonesCollectionWeb.Picture.get_url(picture, :thumb) %>
        <% lightbox_image_url = PhonesCollectionWeb.Picture.get_url(picture, :popup) %>
        <% image_url = PhonesCollectionWeb.Picture.get_url(picture) %>
        <a href="<%= lightbox_image_url %>" data-download-url="<%= image_url %>">
          <img src="<%= thumb_image_url %>" class="thumb"/>
        </a>
      <% end %>
    </div>
  <% end %>
<% end %>